### ISSUE TITLE
investigate into lua API for editing animted lua sprite using tweening

### ISSUE THREAD

**Issue by Zexlo** [Zexlo/FNF-Sonic-EXE-psych-engine-port#13]

**Comment by CarpetBook** [comment]
Added animated title cards to most songs. Need to know if there any other sprites that would need animation by tweening, hence the question label.

**Comment by Zexlo** [comment]
IF super sonic's anims by default don't include him floating up and down im sure tweening would work to re-create that affect

**Comment by CarpetBook** [comment]
That could be done with one (1) single line of Lua in the song script; I'm experimenting with that now... though... he doesn't float up and down in the actual song, does he...? I didn't see it...

**Comment by Zexlo** [comment]
yeah regardless of what anim is used hes always floating
