### ISSUE TITLE
What about HTML5?

### ISSUE THREAD

**Issue by ExodusTheHuman** [Zexlo/FNF-Sonic-EXE-psych-engine-port#14]
Hey, just wondering could you possibly port this to HTML5 so I can play on browser?

**Comment by Zexlo** [comment]
Hey! thanks for taking an interest in our psych port, due to this ports main point being that you get the mod experience in just a folder, hardcoding this to psyche engine and compiling would defeat the point/purpose of the port. sorry about that!

**Comment by CarpetBook** [comment]
I’ll look into hosting an online preview of the mod on our Github page; it shouldn’t be too hard to compile a build for HTLM5.

**Comment by CarpetBook** [comment]
Although, yes, our mod is meant to be added to an existing, compiled version of Psych Engine. It cannot run on its own straight from the repo.

**Comment by ExodusTheHuman** [comment]
Yeah, it's just hard to find mods that can be played on chromebook. Our school district is secure as hell and any unblocked website that gets even a little attention could get blocked.
