### ISSUE TITLE
Triple Trouble charting, 5 key conversion to 4 key

### ISSUE THREAD

**Issue by CarpetBook** [Zexlo/FNF-Sonic-EXE-psych-engine-port#16]
Triple Trouble is a 5 key chart. As far as it's known, there is no way to play 5 key charts in Psych Engine. This chart needs to be fixed to be playable with 4 keys.

**Comment by Zexlo** [comment]
There's a handful of fan charts of this song in the 4K format already so if you aren't willing to chart it yourself Perhaps getting permission to use an existing one could work

**Comment by CarpetBook** [comment]
Probably just gonna do that instead... idk how to chart 💀

**Comment by Zexlo** [comment]
I'll leave finding a good chart and getting permission to you

**Comment by Zexlo** [comment]
This still  needs to be done and my god do i NOT KNOW WHERE TO LOOK LOL

**Comment by LEVIXDDLMAO** [comment]
youtube
