### ISSUE TITLE
Camera moves slightly in the direction of the last arrow pressed

### ISSUE THREAD

**Issue by CarpetBook** [Zexlo/FNF-Sonic-EXE-psych-engine-port#17]
The original mod pans the camera slightly for every arrow press, still centered on the focused character but moving a bit to the side in the direction of the last arrow pressed. Should we add this as an option? It may be possible with a global Lua script...

**Comment by Zexlo** [comment]
If its simple enough to do I don't see why not

**Comment by Zexlo** [comment]
non issue- such a low priority its not worth keeping open
